package Vista;

import com.toedter.calendar.JDateChooser;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

public class CRUD_Solicitante extends javax.swing.JFrame {

    /**
     * Creates new form CRUD_Solicitante
     */
    public CRUD_Solicitante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtcedula_soli = new javax.swing.JTextField();
        txtnombre_soli = new javax.swing.JTextField();
        txtcorreo_soli = new javax.swing.JTextField();
        txtapellido_soli = new javax.swing.JTextField();
        txtcelular_soli = new javax.swing.JTextField();
        txtContra_soli = new javax.swing.JPasswordField();
        rbH = new javax.swing.JRadioButton();
        rbM = new javax.swing.JRadioButton();
        btnCrear = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_Solicitante = new javax.swing.JTable();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        cboxciudad_soli = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtcodigo_solicitn = new javax.swing.JTextField();
        f_nac_soli = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        cbBoxSangre = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        btnCargar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(986, 590));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("USUARIOS SOLICITANTES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 6, 184, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("NOMBRE:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("APELLIDO:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("SEXO:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("CELULAR:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, -1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("CORREO:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("Contraseña:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setText("FECHA DE NACIMIENTO:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("REGISTRO");
        jLabel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 101, -1));
        jPanel1.add(txtcedula_soli, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 130, -1));
        jPanel1.add(txtnombre_soli, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 209, -1));
        jPanel1.add(txtcorreo_soli, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 209, -1));
        jPanel1.add(txtapellido_soli, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 209, -1));
        jPanel1.add(txtcelular_soli, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 209, -1));

        txtContra_soli.setForeground(new java.awt.Color(0, 0, 102));
        txtContra_soli.setText("jPasswordField1");
        jPanel1.add(txtContra_soli, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 210, -1));

        sexo.add(rbH);
        rbH.setForeground(new java.awt.Color(0, 0, 102));
        rbH.setText("Hombre");
        jPanel1.add(rbH, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 100, -1));

        sexo.add(rbM);
        rbM.setForeground(new java.awt.Color(0, 0, 102));
        rbM.setText("Mujer");
        jPanel1.add(rbM, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 90, -1));

        btnCrear.setForeground(new java.awt.Color(0, 0, 102));
        btnCrear.setText("CREAR");
        jPanel1.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 100, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("LISTA");
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 99, -1));

        tabla_Solicitante.setForeground(new java.awt.Color(0, 0, 102));
        tabla_Solicitante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CEDULA", "NOMBRE", "APELLIDO", "FECHA NACIMIENTO", "SEXO", "TELEFONO", "CELULAR", "CORREO", "CONTRASEÑA"
            }
        ));
        jScrollPane1.setViewportView(tabla_Solicitante);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 970, 181));

        btnModificar.setForeground(new java.awt.Color(0, 0, 102));
        btnModificar.setText("MODIFICAR");
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 490, 100, 30));

        btnEliminar.setForeground(new java.awt.Color(0, 0, 102));
        btnEliminar.setText("ELIMINAR");
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 490, 100, 30));

        btnConsultar.setForeground(new java.awt.Color(0, 0, 102));
        btnConsultar.setText("CONSULTAR");
        jPanel1.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, 120, 30));

        jLabel12.setForeground(new java.awt.Color(0, 0, 102));
        jLabel12.setText("CIUDAD:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        cboxciudad_soli.setForeground(new java.awt.Color(0, 0, 102));
        cboxciudad_soli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuenca", "Quito", "Guayaquil", "Loja", "Ambato" }));
        jPanel1.add(cboxciudad_soli, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 210, -1));

        jLabel14.setForeground(new java.awt.Color(0, 0, 102));
        jLabel14.setText("CEDULA:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel15.setForeground(new java.awt.Color(0, 0, 102));
        jLabel15.setText("CODIGO:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 70, -1, -1));
        jPanel1.add(txtcodigo_solicitn, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 70, 80, -1));

        f_nac_soli.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.add(f_nac_soli, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 140, -1));

        jLabel13.setForeground(new java.awt.Color(0, 0, 102));
        jLabel13.setText("TIPO DE SANGRE:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        cbBoxSangre.setForeground(new java.awt.Color(0, 0, 102));
        cbBoxSangre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ORH+", "ORH-", "ARH+", "ARH-", "BRH+", "BRH-", "ABRH+", "ABRH-", " " }));
        jPanel1.add(cbBoxSangre, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 120, -1));

        jLabel16.setForeground(new java.awt.Color(0, 0, 102));
        jLabel16.setText("Direccion:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));
        jPanel1.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 210, -1));

        btnCargar.setForeground(new java.awt.Color(0, 0, 102));
        btnCargar.setText("Cargar");
        jPanel1.add(btnCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        btnRegresar.setForeground(new java.awt.Color(0, 0, 102));
        btnRegresar.setText("REGRESAR");
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnCargar() {
        return btnCargar;
    }

    public JButton getBtnConsultar() {
        return btnConsultar;
    }

    public JButton getBtnCrear() {
        return btnCrear;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public JButton getBtnModificar() {
        return btnModificar;
    }

    public JComboBox<String> getCbBoxSangre() {
        return cbBoxSangre;
    }

    public JComboBox<String> getCboxciudad_soli() {
        return cboxciudad_soli;
    }

    public JDateChooser getF_nac_soli() {
        return f_nac_soli;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JRadioButton getRbH() {
        return rbH;
    }

    public JRadioButton getRbM() {
        return rbM;
    }

    public JTable getTabla_Solicitante() {
        return tabla_Solicitante;
    }

    public JPasswordField getTxtContra_soli() {
        return txtContra_soli;
    }

    public JTextField getTxtapellido_soli() {
        return txtapellido_soli;
    }

    public JTextField getTxtcedula_soli() {
        return txtcedula_soli;
    }

    public JTextField getTxtcelular_soli() {
        return txtcelular_soli;
    }

    public JTextField getTxtcodigo_solicitn() {
        return txtcodigo_solicitn;
    }

    public JTextField getTxtcorreo_soli() {
        return txtcorreo_soli;
    }

    public JTextField getTxtdireccion() {
        return txtdireccion;
    }

    public JTextField getTxtnombre_soli() {
        return txtnombre_soli;
    }

    public ButtonGroup getSexo() {
        return sexo;
    }

    public JButton getBtnRegresar() {
        return btnRegresar;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbBoxSangre;
    private javax.swing.JComboBox<String> cboxciudad_soli;
    private com.toedter.calendar.JDateChooser f_nac_soli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbH;
    private javax.swing.JRadioButton rbM;
    private javax.swing.ButtonGroup sexo;
    private javax.swing.JTable tabla_Solicitante;
    private javax.swing.JPasswordField txtContra_soli;
    private javax.swing.JTextField txtapellido_soli;
    private javax.swing.JTextField txtcedula_soli;
    private javax.swing.JTextField txtcelular_soli;
    private javax.swing.JTextField txtcodigo_solicitn;
    private javax.swing.JTextField txtcorreo_soli;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtnombre_soli;
    // End of variables declaration//GEN-END:variables
}
