/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import com.toedter.calendar.JDateChooser;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author USER
 */
public class CRUD_Comprador extends javax.swing.JFrame {

    /**
     * Creates new form CRUD_compradoor
     */
    public CRUD_Comprador() {
        initComponents();
    }
     public JButton getBtnRegresar() {
        return btnRegresar;
    }

    public JTable getTablaComprador() {
        return TablaComprador;
    }

    public JButton getBtnCargar() {
        return btnCargar;
    }

    public JButton getBtnConsultar() {
        return btnConsultar;
    }

    public JButton getBtnDelete() {
        return btnDelete;
    }

    public JButton getBtnGuardar() {
        return btnGuardar;
    }

    public JRadioButton getBtnH() {
        return btnH;
    }

    public JRadioButton getBtnM() {
        return btnM;
    }

    public JButton getBtnModi() {
        return btnModi;
    }

    public ButtonGroup getButtonGroupSexo() {
        return buttonGroupSexo;
    }

    public JComboBox<String> getCbBoxSangre() {
        return cbBoxSangre;
    }

    public JComboBox<String> getCbboxCiudad() {
        return cbboxCiudad;
    }

    public JDateChooser getjDnacimiento() {
        return jDnacimiento;
    }

    public JTextField getTxtApe() {
        return txtApe;
    }

    public JTextField getTxtCedu() {
        return txtCedu;
    }

    public JTextField getTxtCelular() {
        return txtCelular;
    }

    public JTextField getTxtCorreo() {
        return txtCorreo;
    }

    public JTextField getTxtDirecc() {
        return txtDirecc;
    }

    public JTextField getTxtNomb() {
        return txtNomb;
    }

    public JPasswordField getTxtPass() {
        return txtPass;
    }

    public JComboBox<String> getCbboxEstCivil() {
        return cbboxEstCivil;
    }

    public JComboBox<String> getCbboxMetPagos() {
        return cbboxMetPagos;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCedu = new javax.swing.JTextField();
        txtNomb = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtApe = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        btnH = new javax.swing.JRadioButton();
        btnM = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaComprador = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        cbboxCiudad = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jDnacimiento = new com.toedter.calendar.JDateChooser();
        btnCargar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        cbBoxSangre = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtDirecc = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnModi = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        cbboxMetPagos = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        cbboxEstCivil = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(810, 589));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("COMPRADORES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 14, -1, -1));

        jLabel4.setText("NOMBRE:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 115, -1, -1));

        jLabel5.setText("APELLIDO:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel7.setText("SEXO:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 228, -1, -1));

        jLabel8.setText("CELULAR:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, -1));

        jLabel9.setText("CORREO:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        jLabel10.setText("CONTRASEÑA:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, -1, -1));

        jLabel11.setText("FECHA DE NACIMIENTO:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel6.setText("REGISTRO");
        jLabel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 39, 100, -1));
        jPanel1.add(txtCedu, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 71, 123, -1));
        jPanel1.add(txtNomb, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 105, 209, -1));
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 201, -1));
        jPanel1.add(txtApe, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 147, 209, -1));
        jPanel1.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 200, -1));
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 190, -1));

        buttonGroupSexo.add(btnH);
        btnH.setText("Hombre");
        jPanel1.add(btnH, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 218, 100, -1));

        buttonGroupSexo.add(btnM);
        btnM.setText("Mujer");
        jPanel1.add(btnM, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 218, 90, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel3.setText("LISTA");
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 99, -1));

        TablaComprador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CEDULA", "NOMBRE", "APELLIDO", "FECHA NACIMIENTO", "SEXO", "TIPO SANGRE", "CORREO", "CELULAR", "CIUDAD", "DIRECCION", "CONTRASEÑA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaComprador);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 368, 966, 195));

        jLabel12.setText("CIUDAD:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        cbboxCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuenca", "Quito", "Guayaquil", "Loja", "Ambato" }));
        jPanel1.add(cbboxCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 200, -1));

        jLabel14.setText("CEDULA:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));
        jPanel1.add(jDnacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 140, -1));

        btnCargar.setText("Cargar");
        jPanel1.add(btnCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 70, -1, -1));

        jLabel16.setText("TIPO SANGRE:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 263, -1, -1));

        cbBoxSangre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ORH+", "ORH-", "ARH+", "ARH-", "BRH+", "BRH-", "ABRH+", "ABRH-", " " }));
        jPanel1.add(cbBoxSangre, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 260, 102, -1));

        jLabel2.setText("DIRECCION:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));
        jPanel1.add(txtDirecc, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 200, -1));

        btnConsultar.setText("CONSULTAR");
        jPanel1.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 310, 110, 40));

        btnGuardar.setText("CREAR");
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 313, 90, 34));

        btnModi.setText("MODIFICAR");
        jPanel1.add(btnModi, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 313, 110, 35));

        btnDelete.setText("ELIMINAR");
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 310, 100, 40));

        btnRegresar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/btnRegresar.png"))); // NOI18N
        btnRegresar.setBorder(null);
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 49, -1));

        jLabel17.setText("METODO PAGO:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, -1, -1));

        cbboxMetPagos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "Tarjeta de crédito", "Tarjeta de débito", "Cheque", "Pago en efectivo" }));
        jPanel1.add(cbboxMetPagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 80, 105, -1));

        jLabel18.setText("ESTADO CIVIL:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, -1, -1));

        cbboxEstCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "Soltero", "Casado", "Viudo", "Divorciado" }));
        jPanel1.add(cbboxEstCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 120, 105, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 986, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaComprador;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JRadioButton btnH;
    private javax.swing.JRadioButton btnM;
    private javax.swing.JButton btnModi;
    private javax.swing.JButton btnRegresar;
    private javax.swing.ButtonGroup buttonGroupSexo;
    private javax.swing.JComboBox<String> cbBoxSangre;
    private javax.swing.JComboBox<String> cbboxCiudad;
    private javax.swing.JComboBox<String> cbboxEstCivil;
    private javax.swing.JComboBox<String> cbboxMetPagos;
    private com.toedter.calendar.JDateChooser jDnacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtApe;
    private javax.swing.JTextField txtCedu;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDirecc;
    private javax.swing.JTextField txtNomb;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
